### PR TITLE
in packages without `exports`, look for proxy directories instead

### PR DESCRIPTION
**Pull request by phryneas**
Right now, we're stuck without an `exports` field in `@apollo/client` v3 - we are aiming to add one with v4, but there is no immediate update around the corner.

I'd love to use attw for all our entry points though - so this would look for all `package.json` files within a project and use those as entry points.

### CODE REVIEW

**Comment by andrewbranch** [comment]
Hey, thanks for the contribution! I think I’m ok with this if we add a check that the proxy directory package.json files contain a `"main"` field. I’m thinking about cases where someone drops a `{}` or `{ "type": "module" }` package.json in a directory to change the module format of a particular directory. Those would turn up as a false positive here, although that pattern feels unlikely to occur _without_ root level `exports`.

Have you seen #40? I was planning just to let people pass in a list. Maybe this is a good start though, especially for the web client.

**Comment by phryneas** [comment]
@andrewbranch that sounds like a very good sanity check - I've added it.

I've just seen #40 a few minutes ago - it seems like a good additional way to take, but we want to add this in CI, so something like this that automatically detects new entry points would be much preferred - I'm afraid that at some point we forget to add a new entry point to a manually managed list, and miss errors introduced that way.

**Comment by andrewbranch** [comment]
I think this is good to go. Would you mind adding a changeset with a minor bump for the core package?

**Comment by phryneas** [comment]
Sure, I just added one :)

**Comment by andrewbranch** [comment]
Thanks! This will deploy to the web immediately. I’m hoping to get a couple other random fixes for stuff in today/tomorrow and do an npm release then.

**Comment by phryneas** [comment]
Sounds great :) Thank you for looking at this so fast!

**Pull request merged**
